name: ðŸ§ Linux Builds
on:
  push:
    branches: [master, main]

# Global Settings
env:
  PROJECT_FOLDER: .
  TARGET_PATH: addons/mongo-driver-godot/bin/linux
  TARGET_NAME: libmongo-godot
  TARGET: release

jobs:
  linux-compilation:
    name: Linux Compilation
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: recursive

      # Install all packages (except scons)
      - name: Configure dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libmongoc-1.0-0 libbson-1.0-0 cmake libssl-dev libsasl2-dev libmongoc-dev
      # Use python 3.x release (works cross platform; best to keep self contained in it's own step)
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: "3.x"
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: "x64"

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
      - name: Compilation
        run: |
          echo ------------------------------
          echo Generating Godot Bindings
          echo ------------------------------
          mkdir -v -p ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}
          cd ${{env.PROJECT_FOLDER}}
          cd thirdparty/godot-cpp
          scons platform=linux bits=64 target=${{env.TARGET}} generate_bindings=yes -j4
          cd ../

          echo ------------------------------
          echo Building mongo-c-driver
          echo ------------------------------
          cd mongo-c-driver
          python build/calc_release_version.py > VERSION_CURRENT
          mkdir -v -p cmake-build
          cd cmake-build
          cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_EXAMPLES=OFF -DENABLE_TESTS=OFF ..
          cmake --build .
          sudo cmake --build . --target install
          cd ../../


          echo ------------------------------
          echo Building mongo-cxx-driver
          echo ------------------------------
          cd mongo-cxx-driver/build
          cmake -DBSONCXX_POLY_USE_MNMLSTC=1 -DCMAKE_BUILD_TYPE=Release ..
          sudo cmake --build . --target EP_mnmlstc_core
          cmake --build .
          sudo cmake --build . --target install
          cd ../../../


          echo ------------------------------
          echo Building mongo-driver-godot
          echo ------------------------------
          scons platform=linux target=${{env.TARGET}} target_path=${{env.TARGET_PATH}} target_name=${{env.TARGET_NAME}} -j4
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: linux
          path: ${{env.PROJECT_FOLDER}}/${{env.TARGET_PATH}}
